apiVersion: v1
kind: Service
metadata:
  name: customer-management
spec:
  type: ClusterIP
  selector:
    app: customer-management
  ports:
    - port: {{ .Values.port }}
      targetPort: {{ .Values.port }}
