apiVersion: v1
kind: Service
metadata:
  name: web-server
spec:
  type: NodePort
  selector:
    app: web-server
  ports:
    - port: {{ .Values.port }}
      targetPort: {{ .Values.port }}
      nodePort: {{ .Values.nodePort }}
