image: aura/web-server:latest
imagePullPolicy: Never
replicas: 1
port: 3000
nodePort: 30000

env:
  KAFKA_BROKERS: "kafka:9092"
  CUSTOMER_MANAGEMENT_URL: "http://customer-management:3001"

resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "500m"
    memory: "256Mi"

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 10
  cpuThreshold: "70"
